### PR TITLE
Make CesiumGltf headers public and fix warnings

### LINKED ISSUE #460: Fix warnings in public headers
Somewhere along the way, we started identifying our public header files to CMake as `SYSTEM`. This is the right-ish thing to do for libraries that consume cesium-native via submodule / `add_directory`, so that a project stricter warnings won't flag a bunch of warnings in cesium-native headers. But it means that legitimate warnings in the header files, even when building cesium-native, are ignored. I noticed this because apparently some old versions of CMake don't treat SYSTEM headers specially, and the build had a whole bunch of warnings.

So we should:
* Tweak our CMake config so that the headers are SYSTEM _outside_ cesium-native, but non-system within it.
* Fix the warnings

### PR DESCRIPTION
**Pull request by azrogers**
Closes #460, supersedes #1099. As part of #1004 we stopped marking most of the public headers as SYSTEM so that they would be analyzed by clang-tidy, but we skipped over `CesiumGltf` as the number of warnings didn't seem worth resolving at the time. This PR exposes `CesiumGltf` headers to clang-tidy analysis and compiler warnings, and fixes all the current issues.

### CODE REVIEW

File: CesiumGltf/test/TestPropertyView.cpp [hunk 1]
```diff
@@ -23,7 +23,12 @@
 #include <glm/fwd.hpp>
 
 #include <cstdint>
-#include <ostream>
+// We're not using anything from <iostream> directly in this file, but MSVC
+// removed <iostream> from the <string> header, meaning comparisons between
+// string_view and const char* will fail unless we include it manually. Only on
+// MSVC.
+// https://developercommunity.visualstudio.com/t/visual-studio-2019-compilation-issue/525532#T-N549764.
+#include <iostream>
```
Comment (kring) [inline CesiumGltf/test/TestPropertyView.cpp:31]: Comparing `std::string_view` to `const char*` requires streams for some reason? I can't really imagine why that would be. In any case, the link above mentions you can include `<sstream>`, which I think would be better than `<iostream>`.

**Review by kring — COMMENTED** [review]
Looks good! Just one comment/question.

File: CesiumGltf/test/TestPropertyView.cpp (hunk 1 above)
Comment (azrogers) [reply CesiumGltf/test/TestPropertyView.cpp]: Now that I look at it, I believe it's doctest that's making us include the header: https://github.com/CesiumGS/cesium-native/actions/runs/13976740318/job/39132293455#step:8:631. I've changed it to `<sstream>`.

**Comment by kring** [comment]
Thanks @azrogers!
