### PR TITLE
Fix FeatureCollection visitor to check geometry style

### LINKED ISSUE #672: GeoJSONDocumentRasterOverlay styling not applying
## Description
In Cesium for Unity, when attempting to programmatically update the styling of a `CesiumGeoJsonFeature` or `CesiumGeoJsonObject` within a `CesiumGeoJsonDocument`, the changes are not reflected in the scene. Even after re-assigning the `document` to the `CesiumGeoJsonDocumentRasterOverlay`, the overlay continues to render using the **Default Style** defined in the Inspector's "Styles" section instead of the dynamically assigned `CesiumVectorStyle`.

### Environment

Cesium for Unity version: 1.23.0
Unity Editor Version: Unity 2022 LTS
Operating System:macOS and All

### Reproduction steps

1. Load a `CesiumGeoJsonDocument` into a `CesiumGeoJsonDocumentRasterOverlay`.
2. Access a specific feature or geometry using `GetRootObject().GetObjectAsFeatureCollection()[0].GetGeometry()`.
3. Create a new `CesiumVectorStyle` and `CesiumVectorLineStyle` at runtime.
4. Apply the style using `geometry.SetStyle(allstyle)`.
5. Re-assign the document to the overlay: `_geoJsonOverlay.document = previewDocument;`.
6. **Observed Result:** The line remains the default color/width from the Inspector.
7. **Expected Result:** The line should update to the color/width specified in the code.

## Code Snippet
```csharp
// Accessing the geometry
CesiumGeoJsonObject root = previewDocument.GetRootObject();
CesiumGeoJsonFeature feature = root.GetObjectAsFeatureCollection()[0];
CesiumGeoJsonObject geometry = feature.GetGeometry();

// Defining the new style
CesiumVectorStyle allstyle = new CesiumVectorStyle();
CesiumVectorLineStyle style = new CesiumVectorLineStyle();
style.color = new Color32(225, 22, 255, 255); // Custom Purple
style.width = 20;
allstyle.lineStyle = style;

// Applying style
geometry.SetStyle(allstyle);

// Updating the overlay
_geoJsonOverlay.document = previewDocument; 
// Bug: This does not trigger a visual update with the new style.
```

### PR DESCRIPTION
**Pull request by baruchInsert-tech**
Fix GeoJSON FeatureCollection visitor not reading geometry styles
                                                     
The GeoJsonFeatureCollection visitor in GeoJsonDocumentRasterOverlay was checking the style on the Feature wrapper object instead of the geometry inside it. This caused programmatically-set styles via SetStyle() on geometry objects to be silently ignored when the root object is a FeatureCollection (the common case for GeoJSON documents).

Additionally, the style fallback chain incorrectly fell back to
pFeature->style a second time instead of collection.style, meaning collection-level styles were never consulted.

The GeoJsonFeature visitor already handled this correctly by checking feature.geometry->getStyle(). This change aligns the FeatureCollection visitor with that behavior.

Fixes CesiumGS/cesium-unity#672

## Author Checklist

- [x] I have submitted a Contributor License Agreement (only needed once).
- [x] I have done a full self-review of my code.
- [x] I have updated CHANGES.md with a short summary of my change (for user-facing changes).
- [x] I have added or updated unit tests to ensure consistent code coverage as necessary.
- [x] I have updated the documentation as necessary.

### CODE REVIEW

**Comment by baruchInsert-tech** [comment]
@azrogers please take a look when available 


This means cesium-unreal would also exhibit this issue if a user sets a style on the geometry object within a FeatureCollection and refreshes. It likely hasn't been reported there because users either haven't hit this exact code path, or they set styles at a different level (e.g., on the Feature or the default style, which do work).

File: CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp [hunk 1]
```diff
@@ -81,6 +81,96 @@ CesiumGltf::ImageAsset rasterizeOverlayTile(
   }
   return *pTile->getImage();
 }
+
+CesiumGltf::ImageAsset rasterizeOverlayTileFromDocument(
```
Comment (azrogers) [inline CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp]: This seems to be most of the contents of `rasterizeOverlayTile`, only taking an existing document instead of a path to a GeoJSON file. I would recommend changing the implementation of `rasterizeOverlayTile` to call `rasterizeOverlayTileFromDocument` after the document is loaded, to avoid duplicating the code.

File: CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp [hunk 2]
```diff
@@ -81,6 +81,96 @@ CesiumGltf::ImageAsset rasterizeOverlayTile(
...
+    uint8_t r,
+    uint8_t g,
+    uint8_t b,
+    uint8_t a) {
+  REQUIRE(image.channels == 4);
+  REQUIRE(image.bytesPerChannel == 1);
+  for (int32_t y = 0; y < image.height; y++) {
+    for (int32_t x = 0; x < image.width; x++) {
+      size_t idx = static_cast<size_t>((y * image.width + x) * 4);
+      if (idx + 3 < image.pixelData.size() &&
```
Comment (azrogers) [inline CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp]: I would raise the `idx + 3 < image.pixelData.size()` check up to the top of the function, with something like `REQUIRE(image.width * image.height * image.channels * image.bytesPerChannel == image.pixelData.size())`. If the image doesn't have enough data for the pixels it's supposed to contain that indicates a different issue than the image not having a pixel of that color, so it should be raised as such.

**Comment by azrogers** [comment]
Looks like the core issue here is a copy-and-paste error on my part. Thanks for the fix! A few suggestions for the tests file and a merge conflict that needs resolved, but if that's taken care of we can get this into the next release!

File: CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp (hunk 1 above)
Comment (baruchInsert-tech) [reply CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp]: Thanks! Refactored rasterizeOverlayTile to load the document and then delegate to rasterizeOverlayTileFromDocument, removing the duplicated setup/activation/tile-load code

File: CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp (hunk 2 above)
Comment (baruchInsert-tech) [reply CesiumRasterOverlays/test/TestGeoJsonDocumentRasterOverlay.cpp]: Hoisted it to a REQUIRE(image.width * image.height   * image.channels * image.bytesPerChannel == image.pixelData.size()) at the top of imageHasPixelWithColor, and dropped   the per-pixel idx + 3 < size() guard from the loop.

**Comment by baruchInsert-tech** [comment]
> Looks like the core issue here is a copy-and-paste error on my part. Thanks for the fix! A few suggestions for the tests file and a merge conflict that needs resolved, but if that's taken care of we can get this into the next release!

Done!

**Comment by azrogers** [comment]
Thanks @baruchInsert-tech!
